project_id = "rsdisaisxdglmdmzmkyw"

[functions.generate-template-preview]
verify_jwt = false

[functions.ai-analyze-template-placeholders]
verify_jwt = false

[functions.insert-template-placeholders]
verify_jwt = false

[functions.invite-user]
verify_jwt = true

[functions.generate-boq]
verify_jwt = false

[functions.generate-component]
verify_jwt = false

[functions.analyze-repository]
verify_jwt = false

[functions.fetch-repository-files]
verify_jwt = false

[functions.process-import-session]
verify_jwt = false

[functions.scan-invoice]
verify_jwt = true

[functions.send-message-notification]
verify_jwt = false

[functions.send-approval-notification]
verify_jwt = false

[functions.send-status-update-notification]
verify_jwt = false

[functions.backup-database]
verify_jwt = false

[functions.restore-backup]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.convert-word-to-pdf]
verify_jwt = false
